# Generated by Django 5.2.4 on 2025-08-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
