# Generated by Django 5.2.4 on 2025-08-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='authority',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
