# Generated by Django 5.2.4 on 2025-08-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='category',
            field=models.CharField(choices=[('waiting-room', 'سالن انتظار'), ('office', 'اتاق مطالعه'), ('equipment', 'تجهیزات'), ('exterior', 'نمای بیرونی')], default='office', max_length=20),
        ),
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
